Update bill-of-materials.md
john0312/hitcon-pcb-badge pull request #164
Opened 2024-08-23 14:09 UTC by PichuChen

可能是不可見光所以被忘掉的孩子

2024-08-24 02:23 UTC, Lance798 requested changes
btw, this file is deprecated

2024-08-24 02:23 UTC, Lance798 commented on pcb/bill-of-materials.md
> +- IR LED 940nm: 0603
```suggestion
- IR LED 940nm: SMD2835
```

2024-08-25 02:25 UTC, PichuChen commented
but will the latest version merged into main?

2024-08-30 09:04 UTC, Lance798 commented
the latest version of PCB is on branch `mp-v11c`

2025-06-07 10:13 UTC, closed without merging